/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("$name START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="ledOn",cond=whenDispatch("ledOn"))
					transition(edgeName="t012",targetState="ledOff",cond=whenDispatch("ledOff"))
					transition(edgeName="t013",targetState="ledBlink",cond=whenDispatch("ledBlink"))
				}	 
				state("ledOn") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 Runtime.getRuntime().exec("python ledOn24.py") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="ledOff",cond=whenDispatch("ledOff"))
					transition(edgeName="t015",targetState="ledBlink",cond=whenDispatch("ledBlink"))
				}	 
				state("ledOff") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 Runtime.getRuntime().exec("python ledOff24.py") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="ledOn",cond=whenDispatch("ledOn"))
					transition(edgeName="t017",targetState="ledBlink",cond=whenDispatch("ledBlink"))
				}	 
				state("ledBlink") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 Runtime.getRuntime().exec("python ledBlink24.py") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="ledOn",cond=whenDispatch("ledOn"))
					transition(edgeName="t019",targetState="ledOff",cond=whenDispatch("ledOff"))
				}	 
			}
		}
} 
