/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outred("$name START")
						observeResource("192.168.1.67","8022","ctx_wis","wis","ledState")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="handleUpdateState",cond=whenDispatch("ledState"))
				}	 
				state("handleUpdateState") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("ledState(X)"), Term.createTerm("ledState(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val S=payloadArg(0);
												when (S){
													"blink" -> Runtime.getRuntime().exec("python ledBlink24.py")
													"on"	-> Runtime.getRuntime().exec("python ledOn24.py")
													"off"  	-> Runtime.getRuntime().exec("python ledOff24.py")
													else 	-> Runtime.getRuntime().exec("python ledOff24.py")
												}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="handleUpdateState",cond=whenDispatch("ledState"))
				}	 
			}
		}
} 
