/* Generated by AN DISI Unibo */ 
package it.unibo.md_test_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Md_test_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
		 		var OK=true;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name starts")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: idle")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="test_sua",cond=whenRequest("test_sonar_unload_ash"))
					transition(edgeName="t013",targetState="test_lb",cond=whenRequest("test_led_burning"))
					transition(edgeName="t014",targetState="test_lews",cond=whenRequest("test_led_empty_ws"))
					transition(edgeName="t015",targetState="test_lfas",cond=whenRequest("test_led_full_as"))
				}	 
				state("test_sua") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: test sonar unload ash")
						
						 			OK=true	
						observeResource("localhost","8012","ctx_monitoring_device","sonar","actor_state")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sua_set_empty_ash_storage", cond=doswitch() )
				}	 
				state("sua_set_empty_ash_storage") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,0,ash_unloading,off)" ,"wis" ) 
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sua_unload_ash", cond=doswitch() )
				}	 
				state("sua_unload_ash") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,0,ash_unloaded,off)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="sua_check_not_empty_ash_storage",cond=whenDispatch("actor_state"))
				}	 
				state("sua_check_not_empty_ash_storage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("actor_state(P,V)"), Term.createTerm("actor_state(P,V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								 				OK=(payloadArg(1).toDouble()==(1/3.0))
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end_sua_test", cond=doswitch() )
				}	 
				state("end_sua_test") { //this:State
					action { //it:State
						answer("test_sonar_unload_ash", "test_repl", "test_repl($OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("test_lb") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: test sonar burning")
						
									OK=true	
						forward("set_system_state", "system_state(3,true,false,0,moved_bi,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="lb_check_led_device_off_1",cond=whenReply("led_device_state_repl"))
				}	 
				state("lb_check_led_device_off_1") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lb_set_burning_true", cond=doswitchGuarded({ OK  
					}) )
					transition( edgeName="goto",targetState="end_lb_test", cond=doswitchGuarded({! ( OK  
					) }) )
				}	 
				state("lb_set_burning_true") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,true,0,rp_unloaded,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="lb_check_led_device_blink",cond=whenReply("led_device_state_repl"))
				}	 
				state("lb_check_led_device_blink") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="blinking")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lb_set_burning_false", cond=doswitchGuarded({ OK  
					}) )
					transition( edgeName="goto",targetState="end_lb_test", cond=doswitchGuarded({! ( OK  
					) }) )
				}	 
				state("lb_set_burning_false") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,0,waiting,blinking)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="lb_check_led_device_off_2",cond=whenReply("led_device_state_repl"))
				}	 
				state("lb_check_led_device_off_2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end_lb_test", cond=doswitch() )
				}	 
				state("end_lb_test") { //this:State
					action { //it:State
						answer("test_led_burning", "test_repl", "test_repl($OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("test_lews") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: test sonar empty waste storage")
						
									OK=true	
						forward("set_system_state", "system_state(1,true,false,0,moving_ws,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="lews_check_led_device_off_1",cond=whenReply("led_device_state_repl"))
				}	 
				state("lews_check_led_device_off_1") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lews_set_empty_waste_storage", cond=doswitchGuarded({ OK  
					}) )
					transition( edgeName="goto",targetState="end_lews_test", cond=doswitchGuarded({! ( OK  
					) }) )
				}	 
				state("lews_set_empty_waste_storage") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(0,true,false,0,rp_loaded,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="lews_check_led_device_on",cond=whenReply("led_device_state_repl"))
				}	 
				state("lews_check_led_device_on") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="on")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lews_set_full_waste_storage", cond=doswitchGuarded({OK 
					}) )
					transition( edgeName="goto",targetState="end_lews_test", cond=doswitchGuarded({! (OK 
					) }) )
				}	 
				state("lews_set_full_waste_storage") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,0,rp_loaded,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="lews_check_led_device_off_2",cond=whenReply("led_device_state_repl"))
				}	 
				state("lews_check_led_device_off_2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end_lews_test", cond=doswitch() )
				}	 
				state("end_lews_test") { //this:State
					action { //it:State
						answer("test_led_empty_ws", "test_repl", "test_repl($OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("test_lfas") { //this:State
					action { //it:State
						CommUtils.outcyan("$name: test sonar empty waste storage")
						
									OK=true	
						forward("set_system_state", "system_state(3,true,false,0,unloading_ash,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t023",targetState="lfas_check_led_device_off_1",cond=whenReply("led_device_state_repl"))
				}	 
				state("lfas_check_led_device_off_1") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lfas_set_full_ash_storage", cond=doswitchGuarded({ OK  
					}) )
					transition( edgeName="goto",targetState="end_lfas_test", cond=doswitchGuarded({! ( OK  
					) }) )
				}	 
				state("lfas_set_full_ash_storage") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,1,ash_unloaded,off)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="lfas_check_led_device_on",cond=whenReply("led_device_state_repl"))
				}	 
				state("lfas_check_led_device_on") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="on")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lfas_set_empty_ash_storage", cond=doswitchGuarded({OK 
					}) )
					transition( edgeName="goto",targetState="end_lfas_test", cond=doswitchGuarded({! (OK 
					) }) )
				}	 
				state("lfas_set_empty_ash_storage") { //this:State
					action { //it:State
						forward("set_system_state", "system_state(3,true,false,0,ash_loaded,on)" ,"wis" ) 
						delay(500) 
						request("led_device_state_req", "led_device_state_req" ,"led_device" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t025",targetState="lfas_check_led_device_off_2",cond=whenReply("led_device_state_repl"))
				}	 
				state("lfas_check_led_device_off_2") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_device_state_repl(S)"), Term.createTerm("led_device_state_repl(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												OK=(payloadArg(0)=="off")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end_lfas_test", cond=doswitch() )
				}	 
				state("end_lfas_test") { //this:State
					action { //it:State
						answer("test_led_full_as", "test_repl", "test_repl($OK)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
