/* Generated by AN DISI Unibo */ 
package it.unibo.wis_scheduler

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis_scheduler ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name starts")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t011",targetState="request_activation",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("request_activation") { //this:State
					action { //it:State
						
									val AR=true	
						CommUtils.outyellow("$name: requesting incinerator activation")
						request("activation_req", "activation_req($AR)" ,"incinerator" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="handle_activation_repl",cond=whenReply("activation_repl"))
				}	 
				state("handle_activation_repl") { //this:State
					action { //it:State
						CommUtils.outblack("$name: handling activation repl")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
