services:
  mqttBroker:
    image: eclipse-mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 9001:9001
    volumes:
      - ./MQTT_Broker/config:/mosquitto/config
      - ./MQTT_Broker/:/mosquitto/data
      - ./MQTT_Broker/:/mosquitto/log

  virtualEnv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    expose:
      - 8090
      - 8091
    ports:
      - 8090:8090

  basicRobot:
    image: basicrobot
    ports:
      - 8020:8020
    depends_on:
      - virtualEnv  
  wis:
    image: wis:latest
    ports:
      - 8022:8022
    depends_on:
      - basicRobot
  backend:
    image: wis_backend:latest
    ports:
      - 8085:8085



