/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_device

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Sonar_device ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var O="init"
				var D=13
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name starts")
						delay(500) 
						observeResource("localhost","8012","ctx_monitoring_device","wis","system_state")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="read_mock_data", cond=doswitch() )
				}	 
				state("read_mock_data") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: mock python data: $D")
						emitLocalStreamEvent("sonar_data", "distance($D)" ) 
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="handle_unload_ash",cond=whenDispatch("system_state"))
				}	 
				state("handle_unload_ash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("system_state(RP,ACTIVE,BURNING,ASH_LEVEL,OP_ROBOT_STATE,LED_STATE)"), Term.createTerm("system_state(RP,A,B,L,O)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val NEW_O=payloadArg(4);
												val TO_UPDATE=(NEW_O!=O && O=="ash_unloaded");
												O=NEW_O
								if(  TO_UPDATE  
								 ){  
											 		D-=3; 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="read_mock_data", cond=doswitch() )
				}	 
			}
		}
} 
