/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_device

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Sonar_device ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				lateinit var reader : java.io.BufferedReader
				var working = false
			    lateinit var process : Process	
			    var Distance = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name starts")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="startSonar",cond=whenDispatch("sonarstart"))
				}	 
				state("startSonar") { //this:State
					action { //it:State
						
						    	working = true		
								process = Runtime.getRuntime().exec("python sonar.py")
								reader  = java.io.BufferedReader(  java.io.InputStreamReader(process.getInputStream() ))	
						CommUtils.outblue("SONAR starts")
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="readSonarData", cond=doswitch() )
				}	 
				state("readSonarData") { //this:State
					action { //it:State
						 
								var data = reader.readLine()
								CommUtils.outyellow("$name with python: data = $data"   ) 
								if( data != null ){
									try { 
										val vd = data.toFloat()
										val v  = vd.toInt()
										
										Distance=v;
									} catch(e: Exception){
											CommUtils.outred("$name readSonarDataERROR: $e "   )
									}
								}
								
						emitLocalStreamEvent("sonardata", "distance($Distance)" ) 
						forward("doread", "doread(1)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="stopSonar",cond=whenDispatch("sonarstop"))
					transition(edgeName="t06",targetState="readSonarData",cond=whenDispatchGuarded("doread",{ working   
					}))
					transition(edgeName="t07",targetState="endOfRead",cond=whenDispatchGuarded("doread",{ !working  
					}))
				}	 
				state("endOfRead") { //this:State
					action { //it:State
						
						   	    process.destroy()
						    	if (process.isAlive()) {
						    	    process.destroyForcibly();
						    	}
						       	CommUtils.outred("$tt $name | endOfRead"  )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="startSonar",cond=whenDispatch("sonarstart"))
					transition(edgeName="t09",targetState="stopSonar",cond=whenDispatch("sonarstop"))
				}	 
				state("stopSonar") { //this:State
					action { //it:State
						 process.destroy();  
						CommUtils.outblue("SONAR STOPPED")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="stopSonar",cond=whenDispatch("sonarstop"))
				}	 
			}
		}
} 
