/* Generated by AN DISI Unibo */ 
package it.unibo.wis_state_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis_state_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
		 		var RP = 0
		 		var A = false
		 		var B = false 
		 		var L = 0
		 		val LMAX = 3
		 	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name starts")
						observeResource("localhost","8022","ctx_wis","scale","actor_state")
						observeResource("localhost","8022","ctx_wis","incinerator","actor_state")
						observeResource("localhost","8022","ctx_wis","monitoring_device","actor_state")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_updates", cond=doswitch() )
				}	 
				state("waiting_for_updates") { //this:State
					action { //it:State
						CommUtils.outyellow("$name: waiting for updates...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="update_state",cond=whenDispatch("actor_state"))
					transition(edgeName="t020",targetState="handle_conditions_verified_req",cond=whenRequest("conditions_verified_req"))
				}	 
				state("update_state") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("actor_state(P,V)"), Term.createTerm("actor_state(P,V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val P=payloadArg(0);
												val V=payloadArg(1);
												when (P){
													"incinerator_active" -> A=V.toBoolean()
													"incinerator_burning"-> B=V.toBoolean()
													"waste_storage_rps"  -> RP=V.toInt()
													"ash_storage_level"  -> L=V.toInt()
												}
								CommUtils.outyellow("$name: $P updated")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_updates", cond=doswitch() )
				}	 
				state("handle_conditions_verified_req") { //this:State
					action { //it:State
						
									val RESULT=(RP>0) && (A && !B) && (L<LMAX)
						CommUtils.outyellow("$name: current state { RP:$RP, B:$B, L:$L }, conditions verified: $RESULT")
						answer("conditions_verified_req", "conditions_verified_repl", "conditions_verified_repl($RESULT)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_updates", cond=doswitch() )
				}	 
			}
		}
} 
