FROM openjdk:12.0.2
## ADD extracts the tar
ADD ./build/distributions/GUI_Backend_Sprint3-1.0.tar /
WORKDIR /GUI_Backend_Sprint3-1.0/bin
COPY ./*.pl ./
COPY ./*.json ./
COPY ./*.bin ./
COPY ./*.txt ./
COPY ./*.properties ./
# RUN microdnf install findutils
CMD ["bash", "GUI_Backend_Sprint3"]