FROM openjdk:12.0.2
## ADD extracts the tar
ADD ./build/distributions/wis_tester-1.0.tar /
WORKDIR /wis_tester-1.0/bin
COPY ./*.pl ./
COPY ./*.json ./
COPY ./*.bin ./
COPY ./*.txt ./
COPY ./*.properties ./
# RUN microdnf install findutils
CMD ["bash", "wis_tester"]