services:
  mqttBroker:
    image: eclipse-mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 9001:9001
    volumes:
      - ../MQTT_Broker/config:/mosquitto/config
      - ../MQTT_Broker/:/mosquitto/data
      - ../MQTT_Broker/:/mosquitto/log

  tester:
    image: ghcr.io/b3nny01/wis-tester:latest
    depends_on:
      - mqttBroker

  virtualEnv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    expose:
      - 8090
      - 8091
    ports:
      - 8090:8090

  basicRobot:
    image: docker.io/natbodocker/basicrobot24:1.0
    ports:
      - 8020:8020
    volumes:
      - ./basicrobotConfig.json:/basicrobot24-1.0/bin/basicrobotConfig.json
    depends_on:
      - virtualEnv  
  wis:
    image: ghcr.io/b3nny01/wis-3-mock:latest
    ports:
      - 8022:8022
    volumes:
      - ./wis_system_test.properties:/wis_system-1.0/bin/wis_system.properties
    depends_on:
      - basicRobot
      - mqttBroker
      - tester
  backend:
    image: ghcr.io/b3nny01/wis-backend:latest
    ports:
      - 8085:8085
    depends_on:
      - wis





